trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/Migrations/**'

pool:
  name: LocalPool

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: |
    echo "🔄 Restaurando dependencias..."
    dotnet restore
  displayName: 'Restore'

- script: |
    echo "🔧 Compilando proyecto..."
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: |
    echo "📦 Aplicando migraciones..."
    dotnet ef database update --project TestProjectCore.csproj --startup-project TestProjectCore.csproj
  displayName: 'EF Core Update'

- script: |
    echo "🚀 Publicando aplicación..."
    dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

- script: |
    git config --global user.mail"bymynynimonya@gmail.com"
    git config --global user.name "MAONLY2410"

    echo "Actualización automática $(date)" >> changes.log
    git add changes.log

    git commit -m "Automatizado, toy joya [skip ci]" 
    git push origin HEAD:main
  displayName: "Hacer cambios y pushear"
